### ISSUE TITLE
Handle stderr

### ISSUE THREAD

**Issue by seanrich** [jprichardson/node-suppose#29]
When running the sample code below, I do not get the expected output of responding with 'Please run as root or with sudo'.
```
var suppose = require('suppose');
var fs = require('fs');

suppose('mkdir', ['/mnt/dir'], {debug: fs.createWriteStream('/tmp/debug.txt')})
  .when('Operation not permitted').respond('Please run as root or with sudo')
  .when('Permission denied').respond('Please run as root or with sudo')
  .when('only root can do that').respond('Please run as root or with sudo')
.on('error', function(err){
  console.log(err.message);
})
.end(function(code){
  console.log('ran to the end');
})
```

This never captures the stderr stream when a user attempt to run without correct permissions. I believe this is because it is not handling stderr correctly.

**Comment by piranna** [comment]
The code published on npm handle `stderr` emiting `error` events, the code in master has both `stdout` and `stderr` merged on a single stream by using `node-pty` to exec the commands, but it's a bits unstable yet and needs some improvements with the tests.

On the other hand, your code is broken, since the `when()` calls are not event-like but instead they are sequential, so it needs to fullfill one of the when-respond pairs before move to checking the next one.

**Comment by stevenvachon** [comment]
We can probably close this and move its discussion to #37.

**Comment by piranna** [comment]
> We can probably close this and move its discussion to #37.

I agree, clossing.
